# This workflow was added by CodeSee. Learn more at https://codesee.io/
# This is v2.0 of this workflow file
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_call:
    outputs:
      resource_url:
        description: "The URL of the generated resource."
        value: ${{ jobs.codesee.outputs.resource_url }}
  workflow_dispatch:
name: CodeSee

permissions: read-all

jobs:
  codesee:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Analyze the repo with CodeSee
    outputs:
      resource_url: ${{ steps.step1.outputs.RESOURCE_URL }}
    steps:
      - id: step1
        name: Set env
        run: echo "RESOURCE_URL=UZAIR" >> $GITHUB_ENV
      - uses: Codesee-io/codesee-action@v2
        with:
          codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
          codesee-url: https://app.codesee.io
