name: Setup Node.js environment
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: CHeckout code
      uses: actions/checkout@latest
    - name: workflow_call_code_see
      uses: ./.github/workflows/codesee-arch-diagram.yml
    - name: "Set Up node"
      uses: actions/setup-node@v4.0.0
    - name: "Echo"
      run: echo ${{ env.RESOURCE_URL }}
      
      
