name: Setup Node.js environment
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Set Up node"
      uses: actions/setup-node@v4.0.0
  call:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: "Call codesee"
      uses: ./.github/workflows/codesee-arch-diagram.yml
    - name: "Echo"
      run: echo ${{ env.RESOURCE_URL }}
      
      
