name: Setup Node.js environment
on: 
  workflow_dispatch:
jobs:
  call_codesee:
      uses: ./.github/workflows/meshmap.yml
      with:
        fileName: "manifests"
  test:
    needs: [call_codesee]
    runs-on: ubuntu-latest
    steps:
    - name: "Set Up node"
      uses: actions/setup-node@v4.0.0
    - name: "Echo"
      run: echo ${{needs.call_codesee.outputs.resource_url}}
  

      
      
